### ISSUE TITLE
sign in with github not working 

### ISSUE THREAD

**Issue by wilm42** [thinkful-c11/devcupid#57]
for some reason linking to '/api/auth/github' doesn't work from the landing page, it console logs 'INVALID ENDPOINT' in the server logs

**Comment by tckastanek** [comment]
I placed that console.log in there to detect whenever anyone goes hits the fallback endpoint, i.e. any endpoint that is not explicitly handled by the server.

**Comment by wilm42** [comment]
Theory: because /api/auth/github doesn't send a res, it fires off but then the request falls through to the /* anyway

**Comment by tckastanek** [comment]
Possibly. I just pulled dev and ran through the user flow with visible issues on the front end. However, I logged 'INVALID ENDPOINT' 13 times just clicking through to the profile screen.

But I think you're on the right track with that as the database calls still seem to be working (for me at least), there's just a weird behavior with the requests possibly falling through to the fallback condition and getting routed to the root and we just don't see it on the front end.

**Comment by wilm42** [comment]
extremely weird that you were able to get through the flow, I am not even able to get past the landing page. I branched from dev and I changed nothing about the link or the server.js

**Comment by tckastanek** [comment]
Making a note from the debug session: since the scripts changed in the new version of dev we needed to restart the server and possibly just the bash session. The NODE_ENV=... trigger in the scripts wasn't working.

To avoid this in the future I'll just switch up the logic of the strategyForEnv() fn so that _any_ NODE_ENV variable aside from 'test' (including undefined) will run through the GitHub OAuth strategy.

**Comment by wilm42** [comment]
Oops, closing this - the solve for this was to just reboot the server!
